version: "3.8"

services:
  frontend-user:
    image: ${FRONTEND_USER_IMAGE:-your-dockerhub-username/my-udemy-frontend-user:latest}
    ports:
      - "3000:3000"
    networks:
      - my-udemy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: start-first

networks:
  my-udemy-net:
    driver: overlay
